### ISSUE TITLE
Autodesk Collada exporting crashes Blender (Using Blender 3.2.2)

### ISSUE THREAD

**Issue by Freddi-Marco** [Gabriela-Orzechowska/Blender-MKW-Utilities#2]
This exporting method crashes blender when used, even after rebooting the pc. I've used a combination of all the export settings, but nothing works.

**Comment by Freddi-Marco** [comment]
Also to be noted that Blender generates two files after crashing: a course.dae and a course-pomidor.dae, in addition to a course.fbm folder with all the used textures if "Copy" option was enabled. Both of the .dae files are broken and can't be opened in BrawlCrate, throwing an error in the program itself. Maybe the problem is that i modified the "metallic" and "roughness" properties in a material used in the track, but i'm out now and can't confirm if it is the colporate.

**Comment by MRcodino07** [comment]
After

**Comment by Freddi-Marco** [comment]
Trying it now works normally as usual, but needs a lot of time. Maybe add a progression bar, because as of now it seems more that it is crashing that it is exporting.
