### ISSUE TITLE
Crashes on "tab" key

### ISSUE THREAD

**Issue by TheGamingBram** [Gabriela-Orzechowska/Blender-MKW-Utilities#3]
I was working on a KCL for my track, working on the invis walls. when suddenly the walls disapear and crash blender.

There has been 1 error that has been spamming my blender console, i dont know if that could be a problem.

![image_2023-02-07_202449393](https://user-images.githubusercontent.com/74347226/217344996-f5d3c91d-da25-4a92-96a0-f7e3dceca591.png)

(working with Blender 2.93.13)

**Comment by TheGamingBram** [comment]
Apearently it also might have to do that somehow the blender project got corrupted (i dont know how tho)

**Comment by Gabriela-Orzechowska** [comment]
If Blender crashes when changing modes, it's usually Blender's fault. Sometimes it just can be fixed by doing something different before hand.
The screenshot issue is pretty much harmless.
