### ISSUE TITLE
Error with Exporting KCL

### ISSUE THREAD

**Issue by TheToaste** [Gabriela-Orzechowska/Blender-MKW-Utilities#5]
<img width="667" alt="Screenshot 2023-09-21 202530" src="https://github.com/Gabriela-Orzechowska/Blender-MKW-Utilities/assets/81981383/26751221-acdd-455c-a780-ce79c716cb2d">
I get this error every time I try to export (At the top it says that it's line 2734)

I am using blender 3.3.1

**Comment by Gabriela-Orzechowska** [comment]
Make sure to update wszst to newest version

**Comment by pendertuga83** [comment]
Got the same proble, wszst is on the newest version

**Comment by Lipsum27** [comment]
im getting the exact same issue
