### ISSUE TITLE
The "Export KCL" feature does not appear

### ISSUE THREAD

**Issue by Jonathan-Jude-Walsh** [Gabriela-Orzechowska/Blender-MKW-Utilities#6]
The "Export KCL" feature below "Apply Flag" in the "KCL Utilities" does not appear. I have tested with blender version 4.1 and 3.6 and the same issue persists. I've made sure that I selected the "Blender-MKW-Utilities-v0.1.13.5" as downloaded from the releases and loaded them according to the installation of addons from the "edit preference" tab.
![240721 0849 error](https://github.com/user-attachments/assets/7b914b23-c864-432a-9ba5-42ec7dc7bc71)
![240721 error](https://github.com/user-attachments/assets/aaadddd2-df0e-46a7-8484-4263a6bb1cb0)

**Comment by Gabriela-Orzechowska** [comment]
The issue is mentioned right at the top of KCL window. "Please download Wiimms SZS Tools to Import/Export KCL"
